/**
 * English defaults for content managed through the CMS.
 *
 * The CMS stores Arabic values under the base key and English overrides under
 * `${key}.en`. These defaults keep the English storefront complete before an
 * administrator has entered custom English copy.
 */
export const ENGLISH_CONTENT: Record<string, string> = {
  "home.newsletter.heading": "The UJI Journal",
  "home.newsletter.body": "Everything worth knowing about matcha — rituals, journal stories, and exclusive releases. No noise.",
  "home.hero.eyebrow": "CEREMONIAL JAPANESE MATCHA",
  "home.hero.title": "The real Japanese\nmatcha experience",
  "home.hero.description": "First-grade ceremonial matcha, grown in Shizuoka\nand made for your daily ritual.",
  "home.hero.btn1": "Discover UJI",
  "home.hero.btn2": "Shop matcha",
  "home.products.eyebrow": "THE COLLECTION",
  "home.products.title": "Our products",
  "home.tin.title": "Ceremonial matcha\nof exceptional quality.",
  "home.tin.body": "Authentic Japanese ceremonial-grade matcha, stone-ground from shaded tea leaves for deeper flavor and a richer green color.",
  "home.whyuji.title": "Matcha chosen with care\nfor every preparation.",
  "home.whyuji.body": "Whether you make it for yourself or share it with friends, every UJI matcha is carefully selected from Japan's finest farms to suit every taste and preparation style.",
  "home.whyuji.tile.0.title": "From Shizuoka farms",
  "home.whyuji.tile.0.body": "We select from leading Shizuoka farms, where the finest tea has been grown for centuries.",
  "home.whyuji.tile.1.title": "For every preparation",
  "home.whyuji.tile.1.body": "From matcha lattes to the classic Japanese ritual, there is a matcha for your way.",
  "home.whyuji.tile.2.title": "For everyday moments",
  "home.whyuji.tile.2.body": "Whether you start your day quietly or share a special moment, matcha belongs in every occasion.",
  "home.whyuji.tile.3.title": "100% pure, nothing added",
  "home.whyuji.tile.3.body": "No sugar, artificial flavors, or preservatives. Pure matcha from the heart of Japan to your cup.",
  "home.ritual.quote": "Slow down. Savor matcha.",
  "home.ritual.body": "Matcha is more than a drink. It is a moment to pause, be present, and enjoy the now — from preparing the powder to the first warm sip.",

  "story.hero.eyebrow": "Our story",
  "story.hero.title": "From Shizuoka, Japan\nto your cup",
  "story.hero.description": "It started with a simple question: why was real Japanese matcha so hard to find in the region? The market was filled with culinary powders in beautiful packaging or products with no clear origin. We decided to change that.",
  "story.why.title": "Why is real matcha\nso hard to find?",
  "story.why.body": "That question is why we exist. We looked closely and found three real reasons.",
  "story.why.solution": "We decided to solve the problem at its source: direct purchasing from Shizuoka farms, direct delivery to you, and complete transparency about everything in the tin.",
  "story.why.detail": "That is why every UJI product includes its origin story. That is why we name the farm. That is why we explain the difference between every grade. Transparency is the foundation of trust.",
  "story.shizuoka.title": "Shizuoka farms",
  "story.shizuoka.body": "Set against Mount Fuji, Shizuoka is one of Japan's most renowned tea-growing regions. Its mild climate, rich volcanic soil, and morning mist create matcha with deep flavor and exceptional quality.",
  "story.brand.title": "Our brand",
  "story.brand.body": "UJI MATCHA is more than a brand; it is a bridge between two cultures. We carry the spirit of Japanese matcha in every tin: matcha grown in Shizuoka with the same ceremonial quality enjoyed in Japan.",
  "story.cta.title": "Be part of the story",
  "story.cta.body": "Join our newsletter and be the first to hear what is new.",
  "story.cta.btn": "Shop now →",

  "ritualpage.hero.eyebrow": "THE MATCHA RITUAL",
  "ritualpage.hero.title": "The art of preparing\nauthentic matcha",
  "ritualpage.hero.description": "Five steps that turn matcha from a powder into a sensory experience. Learn them once and make them for a lifetime.",
  "ritualpage.tips.title": "Pro tips",
  "ritualpage.cta.title": "Ready for your ritual?",
  "ritualpage.cta.body": "Get UJI ceremonial matcha and begin today.",
  "ritualpage.cta.btn": "Shop matcha →",
  "ritualpage.tip.0.title": "Temperature",
  "ritualpage.tip.0.body": "70–80° for pure matcha, 80–85° for lattes",
  "ritualpage.tip.1.title": "Measure",
  "ritualpage.tip.1.body": "3–4 grams per 40 ml of water",
  "ritualpage.tip.2.title": "Whisk",
  "ritualpage.tip.2.body": "Store your whisk in a holder after use to keep it lasting longer",
  "ritualpage.tip.3.title": "Storage",
  "ritualpage.tip.3.body": "Seal the tin and keep it refrigerated, away from light",
  "ritualpage.step.0.desc": "Sift one teaspoon of matcha (3–4 grams) into your chawan to break up clumps and ensure a perfectly smooth cup.",
  "ritualpage.step.0.detail": "Many people skip sifting, but it is the difference between a smooth cup and a grainy one.",
  "ritualpage.step.1.desc": "Heat the water to 70–80°C. Boiling water can burn the matcha and give the cup an unwanted bitterness.",
  "ritualpage.step.1.detail": "Let boiled water cool for two minutes, or use a thermometer for precision.",
  "ritualpage.step.2.desc": "Add 40 ml of water and whisk quickly in a W motion for 30 seconds until a fine foam forms on the surface.",
  "ritualpage.step.2.detail": "Use a bamboo chasen from the center outward, never in a circular motion.",
  "ritualpage.step.3.desc": "For a matcha latte, slowly add steamed milk over the concentrated matcha. For classic matcha, drink it as it is.",
  "ritualpage.step.3.detail": "Plant-based milk, especially oat or almond, brings out a distinctive flavor with matcha.",
  "ritualpage.step.4.desc": "Before your first sip, breathe in the aroma, notice the emerald color, and feel the warmth in your hands. This is the ritual.",
  "ritualpage.step.4.detail": "Ceremonial matcha has three layers of flavor: grassy, then sweet, then umami.",

  "wholesale.hero.eyebrow": "FOR CAFÉS & BUSINESSES",
  "wholesale.hero.title": "Serve matcha\nas your customers deserve",
  "wholesale.hero.description": "From ready-to-use recipes to team training, we build a matcha experience that keeps your customers coming back.",
  "wholesale.hero.btn": "Get in touch →",
  "wholesale.hero.redirect": "You will be redirected in a few seconds",
  "wholesale.pillar.0.title": "Ceremonial matcha",
  "wholesale.pillar.0.body": "Top-grade Japanese matcha for premium drinks and distinctive menus.",
  "wholesale.pillar.1.title": "Recipes & training",
  "wholesale.pillar.1.body": "We provide ready recipes and train your team so every cup is served correctly.",
  "wholesale.pillar.2.title": "Ongoing support",
  "wholesale.pillar.2.body": "We do not disappear after the first order. We stay with you through every stage of growth.",
  "wholesale.cta.title": "Tell us about your business",
  "wholesale.cta.body": "Business name · industry · expected usage",

  "policy.return.title": "Returns & exchanges",
  "policy.return.intro": "For everyone's safety, food products cannot be returned or exchanged unless they arrive damaged. Damaged products must be unused, unopened, and in their original condition.",
  "policy.return.note": "Note: Damage claims are reviewed and verified by the relevant team.",
  "policy.privacy.title": "Privacy policy",
  "policy.privacy.intro": "This privacy policy explains what information we collect about you, how we use it, and the steps we take to keep it secure.",
  "policy.privacy.whatinfo": "When you create an account, we collect registration details such as your name, email address, shipping address, and phone number. We also collect information about your purchases and preferences.",
  "policy.privacy.howuse": "We record, use, and protect your personal information in accordance with applicable data protection law and this privacy policy. We primarily use it to provide our products and services, including to:",
  "policy.privacy.secure": "This information is stored securely and will not be shared with or sold to any outside party.",
  "policy.privacy.cookies": "Like many other websites, we may use a standard technology called cookies. Cookies are small files saved by your browser that help us understand how you use this website and improve your experience.",
  "policy.privacy.changes": "We reserve the right to change our security and privacy policies at any time. We recommend reviewing this page regularly for the latest version.",
  "policy.privacy.footer": "This website follows the privacy policy of its processing provider, Al Qudra Technical Information and Communications Co. (Zid).",
  "policy.cta.title": "Have a question?",
  "policy.cta.body": "Our team is ready to help whenever you need us.",
  "policy.cta.btn": "Chat on WhatsApp",
};